### ISSUE TITLE
Add support for rectangular videos

### ISSUE THREAD

**Issue by TaylorLL98** [DIYnamics/digipyro#8]
When trying to use digipyro on a rectangular video, I get the following error:

`Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64_qbz5n2kfra8p0\lib\tkinter\_init__.py", line 1883, in _call_
    return self.func(*args)
  File "DigiPyRo.py", line 466, in start
    frame = cv2.resize(frame,(width,height), interpolation = cv2.INTER_CUBIC)
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4045: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'`

and the output file cannot be opened.  If I crop my video to be square, the issue is resolved.  Please add support for rectangular videos in the future.

**Comment by spencerahill** [comment]
Thanks for the feature request.  Agreed, we should absolutely support rectangular video.

For now, I'd put that at the second level of priority, where the first level is the more basic refactor + overhaul of the codebase and package structure.  We have to get the internals in good working order first, then we'll be in a good place to start adding features like this.
